export const subcategories = {
  techInnovation: [
    'Tech Innovation',
    'Data Science & Analytics',
    'Software Testing / QA',
    'Database & Storage',
    'Technical & Career-Oriented',
    'Digital Transformation',
    'Emerging Tech & Research',
    'Space Tech',
  ],
  aiAndMachineLearning: [
    'AI & Machine Learning',
    'DevOps & Cloud',
    'Cybersecurity',
    'Robotics & IoT',
    'Augmented Reality (AR) / VR',
  ],
  webDevelopment: [
    'Web Development',
    'Mobile Development',
    'Blockchain & Web3',
    'Web & Media',
    'UI/UX Design',
    'SEO & Digital Marketing',
  ],
  companyCulture: [
    'Company Culture',
    'Technical & Career-Oriented',
    'Career & Education',
    'Career Guidance',
    'Quantum Computing',
    'People & Culture',
    'Women in Tech',
    'Remote Work Life',
    'Work-Life Balance',
    'HR & Hiring Trends',
  ],
  industryTrends: [
    'Industry Trends',
    'Resume & Interview Tips',
    'Study Abroad / MS in CS',
    'Campus Placements',
    'Upskilling & Certifications',
    'Industry & Business',
    'Product Management',
    'Market Analysis',
    'VC & Funding News',
    'Content Creation / Tech Writing',
    'Space Tech',
    'Bioinformatics / Health Tech',
    'Remote Work Life',
    'Tech Events / Hackathons',
  ],
  caseStudies: [
    'Case Studies',
    'Startup Spotlight',
    'Open Source Projects',
    'Tech Events / Hackathons',
    'Learning Resources',
    "Tutorials & How-to's",
    'Project Ideas',
    'Cheat Sheets / Quick Guides',
    'Tech Books & Tools',
  ],
};

export const cardcategories = {
  "career-jobs": {
    name: "Career & Jobs",
    image: "/lovable-uploads/Carrer & Jobs.png",
    link: "/jobs/today",
  },
  "games": {
    name: "Games",
    image: "/lovable-uploads/Games.png",
    link: "/gamezone",
  },
  "tech-hub": {
    name: "Tech Hub",
    image: "/lovable-uploads/techhub.png",
    link: "/techhub",
  },
    "exams": {
    name: "Exams",
    image: "/lovable-uploads/exam.png",
    link: "/jobs/internships",
  },
  "aptitude": {
    name: "Aptitude",
    image: "/lovable-uploads/Aptitude.png",
    link: "/category/case-studies",
  },
  "tech-industry": {
    name: "Tech Industry",
    image: "/lovable-uploads/Tech Industry.png",
    link: "/category/tech-innovation",
  },
  "web-development": {
    name: "Web Development",
    image: "/lovable-uploads/Web Developement.png",
    link: "/category/web-development",
  },
};
