export const subcategories = {
  techInnovation: [
    'Tech Innovation',
    'Data Science & Analytics',
    'Software Testing / QA',
    'Database & Storage',
    'Technical & Career-Oriented',
    'Digital Transformation',
    'Emerging Tech & Research',
    'Space Tech',
  ],
  aiAndMachineLearning: [
    'AI & Machine Learning',
    'DevOps & Cloud',
    'Cybersecurity',
    'Robotics & IoT',
    'Augmented Reality (AR) / VR',
  ],
  webDevelopment: [
    'Web Development',
    'Mobile Development',
    'Blockchain & Web3',
    'Web & Media',
    'UI/UX Design',
    'SEO & Digital Marketing',
  ],
  companyCulture: [
    'Company Culture',
    'Technical & Career-Oriented',
    'Career & Education',
    'Career Guidance',
    'Quantum Computing',
    'People & Culture',
    'Women in Tech',
    'Remote Work Life',
    'Work-Life Balance',
    'HR & Hiring Trends',
  ],
  industryTrends: [
    'Industry Trends',
    'Resume & Interview Tips',
    'Study Abroad / MS in CS',
    'Campus Placements',
    'Upskilling & Certifications',
    'Industry & Business',
    'Product Management',
    'Market Analysis',
    'VC & Funding News',
    'Content Creation / Tech Writing',
    'Space Tech',
    'Bioinformatics / Health Tech',
    'Remote Work Life',
    'Tech Events / Hackathons',
  ],
  caseStudies: [
    'Case Studies',
    'Startup Spotlight',
    'Open Source Projects',
    'Tech Events / Hackathons',
    'Learning Resources',
    "Tutorials & How-to's",
    'Project Ideas',
    'Cheat Sheets / Quick Guides',
    'Tech Books & Tools',
  ],
};
