// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhtoixhnzbdrgiqynxmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5odG9peGhuemJkcmdpcXlueG1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NjQzNTUsImV4cCI6MjA2MzE0MDM1NX0.QpR5AcGogQnJOqg_weZ6ubnorJk2HZb6HUUGQ6fRscU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);